# Dependencies

# Permalinks
permalink:        pretty


# Setup
title:            Richa Gupta's Website
tagline:          ''
description:      'Website for showcasing my projects.' 
url:              "https://richagupta0211.github.io/Natural-Language-Processing-Python/"
baseurl:          "/Natural-Language-Processing-Python"


paginate:         5

# Custom vars
version:          0.0.0

github:
  repo:           
